name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Chaganti-Reddy
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot, vue, scala, ejs, jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_indepth: no
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages
          plugin_wakatime_days: 7
          plugin_wakatime_user: current

          plugin_leetcode: yes
          plugin_leetcode_user: chagantivenkataramireddy1
          plugin_leetcode_sections: solved, skills
          plugin_leetcode_limit_skills: 6

          plugin_habits: yes
          plugin_habits_from: 200       
          plugin_habits_days: 14        
          plugin_habits_facts: no
          plugin_habits_charts: yes    

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0 

          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons

          plugin_rss: yes
          plugin_rss_source: https://karnablog.netlify.app/index.xml
          plugin_rss_limit: 3

          plugin_traffic: yes
