name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: Chaganti-Reddy
          template: classic       
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          config_twemoji: yes
          config_octicon: yes
          
          repositories_affiliations: owner, collaborator
          repositories_forks: no
          
          plugin_followup: yes
          plugin_followup_sections: user 
          plugin_followup_indepth: yes
          
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15

          plugin_calendar: yes
          plugin_calendar_limit: 2

          plugin_discussions: no
          plugin_discussions_categories: yes

          plugin_gists: yes

          plugin_lines: no
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          plugin_notable: no
          plugin_notable_from: user
          plugin_notable_types: commit
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_user: current
          plugin_wakatime_repositories_visibility: all 

          plugin_leetcode: yes
          plugin_leetcode_user: chagantivenkataramireddy1
          plugin_leetcode_sections: solved
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_limit_recent: 2

          plugin_habits: yes
          plugin_habits_from: 200       
          plugin_habits_days: 14
          plugin_habits_facts: yes      
          plugin_habits_charts: yes
          plugin_habits_trim: yes

          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
          plugin_topics_sort: stars

          plugin_rss: yes
          plugin_rss_source: https://karnablog.netlify.app/index.xml
          plugin_rss_limit: 5

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: no  
          plugin_achievements_threshold: C
          plugin_achievements_limit: 0  
