name: Metrics
on:
  # Update every 24 hours
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual trigger
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Chaganti-Reddy
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot, vue, scala, ejs
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_indepth: no
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages
          plugin_wakatime_days: 7

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
