name: Metrics

on:
  schedule: [{cron: "0 0/24 * * *"}]
  workflow_dispatch:
  # push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: left profile 
        uses: stalomeow/metrics@projects-v2
        with:
          token: ${{ secrets.METRICS_TOKEN }} 
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics-left.svg
          user: Chaganti-Reddy
          template: classic
          config_timezone: Asia/Shanghai
          
          base: header, activity, community, repositories
          repositories_affiliations: owner, collaborator, organization_member
          
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 90
          
          config_padding: 0, 8 + 11%
          config_order: base.header, base.activity+community, base.repositories, languages, habits, lines

      - name: right profile 
        uses: stalomeow/metrics@projects-v2
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics-right.svg
          user: Chaganti-Reddy
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_achievements: yes
          plugin_achievements_threshold: X
          plugin_achievements_limit: 8
          plugin_achievements_display: detailed
          
          config_padding: 0, 8 + 11%
          config_order: wakatime, isocalendar, achievements
